achievementData = {
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"tutorial", "normal50", "normal100", "normal250", "normal500", "hardcore50", "hardcore100", "hardcore250", "hardcore500", "cars50", "cars100", "cars250", "cars500"},
	achievements = {
		{
			id = "tutorial",
			name = "Crossing the Line",
			description = "Complete the Tutorial",
			isSecret = false,
			scoreValue = 1,
		},
		{
			id = "normal50",
			name = "Normal Mode Novice",
			description = "Score 50 points in Normal Mode",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "normal100",
			name = "Normal Mode Expert",
			description = "Score 100 points in Normal Mode",
			isSecret = false,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "normal250",
			name = "Normal Mode Master",
			description = "Score 250 points in Normal Mode",
			isSecret = false,
			progressMax = 250,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "normal500",
			name = "Normal Mode Legend",
			description = "Score 500 points in Normal Mode",
			isSecret = false,
			progressMax = 500,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hardcore50",
			name = "Hardcore Mode Novice",
			description = "Score 50 points in Hardcore Mode",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hardcore100",
			name = "Hardcore Mode Expert",
			description = "Score 100 points in Hardcore Mode",
			isSecret = false,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hardcore250",
			name = "Hardcore Mode Master",
			description = "Score 250 points in Hardcore Mode",
			isSecret = false,
			progressMax = 250,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "hardcore500",
			name = "Hardcore Mode Legend",
			description = "Score 500 points in Hardcore Mode",
			isSecret = false,
			progressMax = 500,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "cars50",
			name = "Passing the Time",
			description = "Let 50 cars pass successfully",
			isSecret = false,
			progressMax = 50,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "cars100",
			name = "Vroom Vroom!",
			description = "Let 100 cars pass successfully",
			isSecret = false,
			progressMax = 100,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "cars250",
			name = "Lots of Emissions",
			description = "Let 250 cars pass successfully",
			isSecret = false,
			progressMax = 250,
			progressIsPercentage = true,
			scoreValue = 1,
		},
		{
			id = "cars500",
			name = "Burning Rubber",
			description = "Let 500 cars pass successfully",
			isSecret = false,
			progressMax = 500,
			progressIsPercentage = true,
			scoreValue = 1,
		},
	}
}